version: '3'
services:
  server:
    container_name: flask
    build: ./server
    ports: ['5000:5000']
    volumes:
      - ./server:/usr/src/app
    restart: always
    # environment:
    #   - FLASK_ENV=development
    #   - FLASK_APP=run.py
    #   - FLASK_DEBUG=1
    environment:
      ENV: DEVELOPMENT
      DB_USERNAME: username
      DB_PASSWORD: password
      DB_DATABASE: database_name
      DB_HOST: localhost
    links:
      - database
  database:
    container_name: database_name
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_DATABASE: database_name
      MYSQL_USER: username
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    ports:
      - '3306:3306'
    expose:
      - '3306'
    volumes:
      - flask-db:/var/lib/mysql

volumes:
  flask-db: